L=8
python ed_ising.py ${L} 0.05
python ed_ising.py ${L} 0.1
python ed_ising.py ${L} 0.15
python ed_ising.py ${L} 0.2
python ed_ising.py ${L} 0.25
python ed_ising.py ${L} 0.3
python ed_ising.py ${L} 0.35
python ed_ising.py ${L} 0.4
python ed_ising.py ${L} 0.45
python ed_ising.py ${L} 0.5
python ed_ising.py ${L} 0.55
python ed_ising.py ${L} 0.6
python ed_ising.py ${L} 0.65
python ed_ising.py ${L} 0.7
python ed_ising.py ${L} 0.75
python ed_ising.py ${L} 0.8
python ed_ising.py ${L} 0.85
python ed_ising.py ${L} 0.9
python ed_ising.py ${L} 0.95
